# Generated by Django 4.0.6 on 2022-12-10 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('account_type', models.CharField(choices=[('Customer', 'Customer'), ('Deliveryman', 'Deliveryman'), ('Dealer', 'Dealer')], default='Customer', max_length=11)),
                ('address_1', models.CharField(max_length=128, verbose_name='address')),
                ('address_2', models.CharField(blank=True, max_length=128, verbose_name="address cont'd")),
                ('zip_code', models.CharField(default='00000', max_length=5, verbose_name='zip code')),
                ('city', smart_selects.db_fields.ChainedForeignKey(chained_field='state', chained_model_field='region', on_delete=django.db.models.deletion.CASCADE, to='cities_light.city')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities_light.region')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
