# Generated by Django 4.0.6 on 2022-12-11 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('Customer', 'Customer'), ('Deliveryman', 'Deliveryman'), ('Dealer', 'Dealer')], default='Customer', max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('<django.db.models.fields.CharField>', 'Possible Country')], default=None, max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('flat_num', models.PositiveIntegerField(blank=True, null=True)),
                ('street_number', models.CharField(max_length=5)),
                ('street', models.CharField(max_length=32)),
                ('city', models.CharField(max_length=32)),
                ('zip_code', models.PositiveIntegerField()),
                ('phone_number', models.PositiveIntegerField()),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Users.country')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
