# Generated by Django 4.0.6 on 2023-01-02 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default=None, max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('account_type', models.CharField(max_length=50)),
                ('flat_num', models.PositiveIntegerField(blank=True, null=True)),
                ('street_number', models.CharField(max_length=5)),
                ('street', models.CharField(max_length=32)),
                ('city', models.CharField(max_length=32)),
                ('zip_code', models.PositiveIntegerField()),
                ('phone_number', models.PositiveIntegerField(blank=True, unique=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Users.country')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
