# Generated by Django 4.0.6 on 2022-12-11 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country',
            field=models.CharField(default=None, max_length=35),
        ),
        migrations.AlterField(
            model_name='userprofileinfomodel',
            name='country',
            field=models.ForeignKey(default='NULL', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Users.country'),
        ),
    ]
