# Generated by Django 4.0.6 on 2023-01-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
