# Generated by Django 4.0.6 on 2022-12-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('Customer', 'Customer'), ('Deliveryman', 'Deliveryman'), ('Dealer', 'Dealer')], default='Customer', max_length=11)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofileinfomodel',
            name='account_type',
        ),
        migrations.AlterField(
            model_name='userprofileinfomodel',
            name='address_2',
            field=models.CharField(blank=True, max_length=128, verbose_name='additional address'),
        ),
    ]
