# Generated by Django 4.0.6 on 2023-01-02 21:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Fishing Rod', 'Fishing Rod'), ('Spinning Wheel', 'Spinning Wheel'), ('Chair', 'Chair'), ('Natural Bait', 'Natural Bait'), ('Crankbait', 'Crankbait'), ('Twister', 'Twister'), ('Rubber Bait', 'Rubber Bait')], max_length=50)),
                ('brand', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('price', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.PositiveIntegerField(null=True)),
                ('orderdate', models.DateTimeField(blank=True, null=True)),
                ('approved_order', models.BooleanField(default=False)),
                ('basket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basket_items', to='PoShopApp.equipment')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Users.profile')),
            ],
        ),
    ]
