# Generated by Django 4.0.6 on 2022-12-11 16:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=64)),
                ('brand', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Twister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('price', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('twister_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twisters', to='PoShopApp.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='Spinning_wheel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('price', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('spinnig_wheel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spinning_wheels', to='PoShopApp.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='Rubber_bait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('price', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('rubber_bait_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubber_baits', to='PoShopApp.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='Natural_bait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('price', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('bait_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='natural_baits', to='PoShopApp.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='Fishing_rod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('price', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)])),
                ('rod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fishing_rods', to='PoShopApp.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='Crankbait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('price', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('crankbait_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crankbaits', to='PoShopApp.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='Chair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('price', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('chair_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chairs', to='PoShopApp.equipment')),
            ],
        ),
    ]
