# Generated by Django 4.0.6 on 2023-01-02 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PoShopApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
