# Generated by Django 4.1 on 2022-11-17 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("PoShopApp", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="UserLogin", new_name="UserSignIn",),
    ]
