# Generated by Django 4.0.6 on 2023-01-02 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PoShopApp', '0002_alter_equipment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(default='Null', max_length=128, null=True),
        ),
    ]
