# Generated by Django 4.0.6 on 2023-01-04 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PoShopApp', '0002_order_current_item_price_alter_order_approved_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='basket',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='current_item_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
