# Generated by Django 4.0.6 on 2023-01-02 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PoShopApp', '0004_alter_equipment_brand_alter_equipment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='category',
            field=models.CharField(choices=[('Fishing Rod', 'Fishing Rod'), ('Spinning Wheel', 'Spinning Wheel'), ('Chair', 'Chair'), ('Natural Bait', 'Natural Bait'), ('Crankbait', 'Crankbait'), ('Twister', 'Twister'), ('Rubber Bait', 'Rubber Bait'), ('Wobblers', 'Wobblers')], max_length=50),
        ),
    ]
